<?php if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Land_document_type extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Land_document_type_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','land_document_type/land_document_type_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Land_document_type_model->json();
    }

    public function read($id) 
    {
        $row = $this->Land_document_type_model->get_by_id($id);
        if ($row) {
            $data = array(
		'land_document_type_id' => $row->land_document_type_id,
		'land_document_type_name' => $row->land_document_type_name,
		'land_document_type_extra' => $row->land_document_type_extra,
	    );
            $this->template->load('template','land_document_type/land_document_type_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('land_document_type'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('land_document_type/create_action'),
	    'land_document_type_id' => set_value('land_document_type_id'),
	    'land_document_type_name' => set_value('land_document_type_name'),
	    'land_document_type_extra' => set_value('land_document_type_extra'),
	);
        $this->template->load('template','land_document_type/land_document_type_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'land_document_type_name' => $this->input->post('land_document_type_name',TRUE),
		'land_document_type_extra' => $this->input->post('land_document_type_extra',TRUE),
	    );

            $this->Land_document_type_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('land_document_type'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Land_document_type_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('land_document_type/update_action'),
		'land_document_type_id' => set_value('land_document_type_id', $row->land_document_type_id),
		'land_document_type_name' => set_value('land_document_type_name', $row->land_document_type_name),
		'land_document_type_extra' => set_value('land_document_type_extra', $row->land_document_type_extra),
	    );
            $this->template->load('template','land_document_type/land_document_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('land_document_type'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('land_document_type_id', TRUE));
        } else {
            $data = array(
		'land_document_type_name' => $this->input->post('land_document_type_name',TRUE),
		'land_document_type_extra' => $this->input->post('land_document_type_extra',TRUE),
	    );

            $this->Land_document_type_model->update($this->input->post('land_document_type_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('land_document_type'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Land_document_type_model->get_by_id($id);

        if ($row) {
            $this->Land_document_type_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('land_document_type'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('land_document_type'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('land_document_type_name', 'land document type name', 'trim|required');
	$this->form_validation->set_rules('land_document_type_extra', 'land document type extra', 'trim|required');

	$this->form_validation->set_rules('land_document_type_id', 'land_document_type_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Land_document_type.php */
/* Location: ./application/controllers/Land_document_type.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-04 04:19:42 */
/* http://harviacode.com */