<?php if (!defined('BASEPATH')) exit ('No direct script access allowed');

class Land_document_type_model extends CI_Model
{

    public $table = 'land_document_type';
    public $id = 'land_document_type_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('land_document_type_id,land_document_type_name,land_document_type_extra');
        $this->datatables->from('land_document_type');
        $this->datatables->where('land_document_category_id=1');
        //add this line for join
        //$this->datatables->join('table2', 'land_document_type.field = table2.field');
        $this->datatables->add_column('action', 
            anchor(site_url('land_document_type/update/$1'),'<i class="anticon anticon-edit" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-icon btn-sm btn-rounded'))
            //." ".anchor(site_url('land_document_type/delete/$1'),'<i class="anticon anticon-delete" aria-hidden="true"></i>','class="btn btn-danger btn-icon btn-sm btn-rounded" onclick="javasciprt: return confirm(\'Are You Sure ?\')"')
        ,'land_document_type_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('land_document_type_id', $q);
	$this->db->or_like('land_document_type_name', $q);
	$this->db->or_like('land_document_type_extra', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('land_document_type_id', $q);
	$this->db->or_like('land_document_type_name', $q);
	$this->db->or_like('land_document_type_extra', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Land_document_type_model.php */
/* Location: ./application/models/Land_document_type_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-04 04:19:42 */
/* http://harviacode.com */