<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_level_model extends CI_Model
{

    public $table = 'tbl_user_level';
    public $id = 'id_user_level';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_user_level,nama_level');
        $this->datatables->from('tbl_user_level');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_user_level.field = table2.field');
        $this->datatables->add_column('action', 
            anchor('#','<i class="anticon anticon-edit" aria-hidden="true"></i>', array('class'=>'btn btn-icon btn-hover btn-sm btn-rounded pull-right edited','data-id'=>'$1'))
        ,'id_user_level');
        // $this->datatables->add_column('action', 
        //     anchor(site_url('userlevel/akses/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-icon btn-hover btn-sm btn-rounded pull-right'))." ".
        //         anchor(site_url('userlevel/update/$1'),'<i class="anticon anticon-edit" aria-hidden="true"></i>', array('class' => 'btn btn-icon btn-hover btn-sm btn-rounded'))." 
        //             ".anchor(site_url('userlevel/delete/$1'),'<i class="anticon anticon-delete" aria-hidden="true"></i>','class="btn btn-icon btn-hover btn-sm btn-rounded" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_user_level');
        return $this->datatables->generate();
    }

    function akses_json($level) {
        $this->datatables->select('tm.id_menu');
        $this->datatables->select('tm.title');
        $this->datatables->select('IF((SELECT ta.id FROM tbl_hak_akses as ta WHERE ta.id_user_level='.$level.' AND ta.id_menu=tm.id_menu),1,0) as checked');
        $this->datatables->where('tm.is_aktif="y"');
        $this->datatables->from('tbl_menu as tm');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_user_level.field = table2.field');

        $this->datatables->add_column('action', 
            '<div class="form-group d-flex align-items-center" style="justify-content: center;margin-bottom: 0;">
                <div class="switch m-r-10">
                    <input type="checkbox" class="checkz" id="switch-$1" data-id="$1" $2>
                    <label for="switch-$1"></label>
                </div>
            </div>'
        ,'id_menu, checked(checked)');

        // $this->datatables->add_column('action', 
        //     anchor(site_url('userlevel/akses/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-icon btn-hover btn-sm btn-rounded pull-right'))." ".
        //         anchor(site_url('userlevel/update/$1'),'<i class="anticon anticon-edit" aria-hidden="true"></i>', array('class' => 'btn btn-icon btn-hover btn-sm btn-rounded'))." 
        //             ".anchor(site_url('userlevel/delete/$1'),'<i class="anticon anticon-delete" aria-hidden="true"></i>','class="btn btn-icon btn-hover btn-sm btn-rounded" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_user_level');
        return $this->datatables->generate();
    }

    

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user_level', $q);
	$this->db->or_like('nama_level', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user_level', $q);
	$this->db->or_like('nama_level', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_level_model.php */
/* Location: ./application/models/User_level_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 06:29:37 */
/* http://harviacode.com */